DEBUG 2024-06-06 06:12:10.068 UTC: 	 CRAB Client version: v3.240416
DEBUG 2024-06-06 06:12:10.069 UTC: 	 Running on: Linux cmslpc105.fnal.gov 3.10.0-1160.99.1.el7.x86_64 #1 SMP Tue Aug 29 10:43:19 CDT 2023 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2024-06-06 06:12:10.069 UTC: 	 Executing command: 'submit'
DEBUG 2024-06-06 06:12:10.069 UTC: 	 Found CRAB cache file /uscms/home/wkarunar/.crab3
INFO 2024-06-06 06:12:10.070 UTC: 	 Will use CRAB configuration file crabConfig_TTree.py
DEBUG 2024-06-06 06:12:10.070 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-06-06 06:12:10.073 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-06-06 06:12:10.073 UTC: 	 Working area '/uscms_data/d3/wkarunar/analysis/run2/CMSSW_10_6_20/src/ZmmYmmAnalyzer_Jesse/singleMuonData/2018/A/crab_TTree_13TeV_mmmm_2018A' already exists 
Please change the requestName in the config file
ERROR 2024-06-06 06:12:10.073 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240416.00/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240416.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240416.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240416.00/lib/CRABClient/Commands/SubCommand.py", line 329, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240416.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/wkarunar/analysis/run2/CMSSW_10_6_20/src/ZmmYmmAnalyzer_Jesse/singleMuonData/2018/A/crab_TTree_13TeV_mmmm_2018A' already exists 
Please change the requestName in the config file
INFO 2024-06-06 06:12:10.076 UTC: 	 Log file is /uscms_data/d3/wkarunar/analysis/run2/CMSSW_10_6_20/src/ZmmYmmAnalyzer_Jesse/singleMuonData/2018/A/crab.log
DEBUG 2024-06-06 08:42:10.696 UTC: 	 CRAB Client version: v3.240416
DEBUG 2024-06-06 08:42:10.697 UTC: 	 Running on: Linux cmslpc105.fnal.gov 3.10.0-1160.99.1.el7.x86_64 #1 SMP Tue Aug 29 10:43:19 CDT 2023 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux 7.9 (Nitrogen)
DEBUG 2024-06-06 08:42:10.697 UTC: 	 Executing command: 'submit'
DEBUG 2024-06-06 08:42:10.697 UTC: 	 Found CRAB cache file /uscms/home/wkarunar/.crab3
INFO 2024-06-06 08:42:10.698 UTC: 	 Will use CRAB configuration file crabConfig_TTree.py
DEBUG 2024-06-06 08:42:10.698 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-06-06 08:42:10.701 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-06-06 08:42:10.701 UTC: 	 Working area '/uscms_data/d3/wkarunar/analysis/run2/CMSSW_10_6_20/src/ZmmYmmAnalyzer_Jesse/singleMuonData/2018/A/crab_TTree_13TeV_mmmm_2018A' already exists 
Please change the requestName in the config file
ERROR 2024-06-06 08:42:10.701 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240416.00/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240416.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240416.00/lib/CRABClient/Commands/submit.py", line 36, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240416.00/lib/CRABClient/Commands/SubCommand.py", line 329, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240416.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/wkarunar/analysis/run2/CMSSW_10_6_20/src/ZmmYmmAnalyzer_Jesse/singleMuonData/2018/A/crab_TTree_13TeV_mmmm_2018A' already exists 
Please change the requestName in the config file
INFO 2024-06-06 08:42:10.703 UTC: 	 Log file is /uscms_data/d3/wkarunar/analysis/run2/CMSSW_10_6_20/src/ZmmYmmAnalyzer_Jesse/singleMuonData/2018/A/crab.log
